### ISSUE TITLE
Note in README that it requires ImageMagick >= 6.3

### ISSUE THREAD

**Issue by ebeigarts** [markevans/dragonfly#181]
I had this error on CentOS 5.8 which has ImageMagick 6.2.8 (and there is no easy way to update the ImageMagick there):

```
NoMethodError (undefined method `downcase' for nil:NilClass):
  dragonfly (0.9.11) lib/dragonfly/image_magick/utils.rb:26:in `identify'
```

It would be nice that it checked the ImageMagick version or at least a note in README.md.
Or raise a better error when `identify` fails, e.g. `identify command is missing or ImageMagick is too old`.

I managed to [patch](https://gist.github.com/2224295) it to work with 6.2.8, this could help someone else who is stuck with CentOS 5.8.
